export const brandsURL = "/api/v1/brands"
export const postOrderURL = "/api/v1/orders"
export const  getInventoryURL = "/api/v1/inventory"
export const reviewsURL = "/api/v1/reviews"
export const getPaymentMethodsURL = "/api/v1/payment-methods"
export const getOrdersURL = "/api/v1/orders"

export const OTPRequestURL = "/api/v1/otp"
export const OTPVerifyURL = "/api/v1/otp/verify"
export const KOKOInitiateURL = "/api/v1/ipg/koko/initiate"
export const PAYHEREInitiateURL = "/api/v1/ipg/payhere/initiate"
export const CODORDERNotificationsURL = "/api/v1/orders"